== Travailler en isolation


=== Création de l'environnement virtuel

Commencons par créer un environnement virtuel, afin d'y stocker les dépendances. Placez-vous dans le répertoire dans lequel vous pourrez stocker tous vos environnements (ces environnements sont indépendants des sources; ils peuvent donc être placés n'importe où sur votre disque - évitez peut-être juste de les mettre pile dans le même répertoire que votre code source). Lancez ensuite la commande `python3 -m venv gwift-env`.

Ceci créera l'arborescence de fichiers suivante, qui peut à nouveau être un peu différente en fonction du système d'exploitation:

[source,bash]
----
fred@aerys:~/Sources/.venvs/gwift-env$ ls
bin  include  lib  lib64  pyvenv.cfg  share
----

Nous pouvons ensuite l'activer grâce à la commande `source gwift-env/bin/activate`.

[source,bash]
----
(gwift-env) fred@aerys:~/Sources/.venvs/gwift-env$ <1>
----






Pour désactiver l'environnement virtuel, il suffit d'utiliser la commande `deactivate`

=== Installation de Django et création du répertoire de travail




=== Gestion des dépendances


=== Matrice de compatibilité

Décrire un fichier tox.ini

[source,bash]
----
$ touch tox.ini
----

=== Licence

Décrire une licence ? :-)

[source,bash]
----
$ touch LICENCE
----

=== Configuration globale

Décrire le fichier setup.cfg

[source,bash]
----
$ touch setup.cfg
----

=== Makefile

Décrire le makefile :)

[source,bash]
----
$ touch Makefile
----

