= Minor swing with Django
Cédric Declerfayt <jaguarondi27@gmail.com>; Fred Pauchet <fred@grimbox.be>
:doctype: book
:toc:
:sectnums:
:chapter-label: Chapitre
:preface-title: Préface
:source-highlighter: rouge
:icons: font

On ne va pas se mentir: il existe enormément de tutoriaux très bien réalisés sur "Comment réaliser une application Django" et autres "Déployer votre code en 2 minutes". On se disait juste que ces tutoriaux restaient relativement haut-niveau et se limitaient à un contexte donné. 

L'idée du texte ci-dessous est de jeter les bases d'un bon développement, en survolant l'ensemble des outils permettant de suivre des lignes directrices reconnues, de maintenir une bonne qualité de code au travers des différentes étapes (du développement au déploiement) et de s'assurer du maintient correct de la base de code, en permettant à n'importe qui de reprendre le développement.

Ces idées ne s'appliquent pas uniquement à Django et à son cadre de travail, ni même au langage Python. Juste que ces deux bidules sont de bons candidats et que le cadre de travail est bien défini et suffisamment flexible.

Django se présente comme un "Framework Web pour perfectionnistes ayant des deadlines" [https://www.djangoproject.com/].

Django suit link:quelques principes[https://docs.djangoproject.com/en/dev/misc/design-philosophies/].

 * Faible couplage et forte cohésion, pour que chaque composant ait son indépendance.
 * Moins de code, plus de fonctionnalités.
 * link:Don't repeat yourself[https://fr.wikipedia.org/wiki/Sec]: ne pas se répéter!
 * Rapidité du développement (après une petite courbe d'apprentissage un peu ardue au début ;-))

Mis côte à côte, l'application de ces principes permet une meilleure stabilité du projet. 

Dans la première partie, on verra comment configurer l'environnement, comment installer Django de manière isolée et comment démarrer un nouveau projet. On verra comment gérer correctement les dépendances, les versions et comment applique un score sur note code.
On verra aussique la configuration proposée par défaut par le framework n'est pas idéale pour la majorité des cas.

Pour cela, on présentera différents outils (mypy, flake8, black, ...), la rédaction de tests unitaires et d'intégration pour limiter les régressions, les règles de nomenclature et de contrôle du contenu, ainsi que les bonnes étapes à suivre pour arriver à un déploiement rapide et fonctionnel avec peu d'efforts.

Dans la seconde partie, on détaillera précisément les étapes de déploiement, avec la description et la configuration de l'infrastructure, ainsi que des exemples concrets de déploiement sur deux distributions principales (Debian et CentOS), ainsi que l'utilisation de Docker et Docker-Compose. 

On abordera également la supervision et la mise à jour d'une application existante, en respectant les bonnes pratiques d'administration système. 

Dans la troisième partie, on abordera les grands principes de modélisation, en suivant les lignes de conduites du cadre de travail. On abordera les concepts clés qui permettent à une application de rester maintenable, les formulaires et leurs validations, les migrations de données et l'administration.

Dans la quatrième partie, on mettra ces concepts en pratique en présentant le développement d'une "vraie" application: définition des tables, gestion des utilisateurs, ... et mise à disposition!

Et tout ça à un seul et même endroit. Oui. :-)

Bonne lecture.

include::part-1-workspace/00-main.adoc[]

include::part-2-deployment/00-main.adoc[]

include::part-3-django-concepts/00-main.adoc[]


= Go Live !

Pour commencer, nous allons nous concentrer sur la création d'un site ne contenant qu'une seule application, même si en pratique le site contiendra déjà plusieurs applications fournies pas django, comme nous le verrons plus loin.

Pour prendre un exemple concret, nous allons créer un site permettant de gérer des listes de souhaits, que nous appellerons `gwift` (pour `GiFTs and WIshlisTs` :)).

La première chose à faire est de définir nos besoins du point de vue de l'utilisateur, c'est-à-dire ce que nous souhaitons qu'un utilisateur puisse faire avec l'application.

Ensuite, nous pourrons traduire ces besoins en fonctionnalités et finalement effectuer le développement

include::gwift/specs.adoc[]

include::gwift/models.adoc[]

include::gwift/tests.adoc[]

include::gwift/key-points.adoc[]

include::gwift/refactoring.adoc[]

include::gwift/user-management.adoc[]

include::gwift/console.adoc[]

include::gwift/metamodel.adoc[]

== Supervision des logs


== feedbacks utilisateurs


include::part-9-bonus/00-main.adoc[]
